# Generated by Django 3.2.6 on 2022-07-05 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='housePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('House', 'House'), ('Appartement', 'Appartement'), ('Villa', 'Villa'), ('Villa', 'Villa')], default='House', max_length=50)),
                ('city', models.CharField(choices=[('Casablanca', 'Casablanca'), ('Rabat', 'Rabat'), ('Marrakech', 'Marrakech'), ('Agadir', 'Agadir'), ('Sale', 'Sale'), ('Kenitra', 'Kenitra'), ('Meknes', 'Meknes'), ('Oujda', 'Oujda'), ('Temara', 'Temara'), ('El Jadida', 'El Jadida'), ('Mohammedia', 'Mohammedia'), ('Tetouan', 'Tetouan'), ('Nador', 'Nador'), ('Safi', 'Safi'), ('Beni Mellal', 'Beni Mellal'), ('Khouribga', 'Khouribga'), ('Bouznika', 'Bouznika'), ('Settat', 'Settat'), ('Abadou', 'Abadou'), ('Abaynou', 'Abaynou'), ('Agadir', 'Agadir'), ('Agadir Melloul', 'Oujda')], default='Casablanca', max_length=50)),
                ('addresse', models.CharField(max_length=100)),
                ('images', models.ImageField(default='no-photo.png', upload_to='images')),
                ('titleAd', models.CharField(max_length=150)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='No Description !!!', max_length=600, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('rooms', models.IntegerField(blank=True, default=0, null=True)),
                ('etage', models.IntegerField(blank=True, default=1, null=True)),
                ('age_proprety', models.CharField(choices=[('New', 'New'), ('1-5 ans', '1-5 ans'), ('6-10 ans', '6-10 ans'), ('11-20 ans', '11-20 ans'), ('+21 ans', '+20 ans')], default='New', max_length=50)),
                ('toilettes', models.IntegerField(blank=True, default=0, null=True)),
                ('living_room', models.IntegerField(blank=True, default=0, null=True)),
                ('total_surface', models.IntegerField(default=0)),
                ('elevator', models.BooleanField(blank=True, default=False, null=True)),
                ('balcony', models.BooleanField(blank=True, default=False, null=True)),
                ('Furniture', models.BooleanField(blank=True, default=False, null=True)),
                ('air_conditioner', models.BooleanField(blank=True, default=False, null=True)),
                ('Furnished', models.BooleanField(blank=True, default=False, null=True)),
                ('Heater', models.BooleanField(blank=True, default=False, null=True)),
                ('concierge', models.BooleanField(blank=True, default=False, null=True)),
                ('terrace', models.BooleanField(blank=True, default=False, null=True)),
                ('cuisine_equipee', models.BooleanField(blank=True, default=False, null=True)),
                ('securite', models.BooleanField(blank=True, default=False, null=True)),
                ('Parking', models.BooleanField(blank=True, default=False, null=True)),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
