# Generated by Django 3.2.6 on 2022-07-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepost',
            name='category',
            field=models.CharField(choices=[('House', 'House'), ('Appartement', 'Appartement'), ('Villa', 'Villa'), ('Duplex', 'Duplex')], default='House', max_length=50),
        ),
    ]
