# Generated by Django 3.2.6 on 2022-07-05 00:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeApp', '0002_alter_housepost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='housepost',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='savePost', to=settings.AUTH_USER_MODEL),
        ),
    ]
