# Generated by Django 3.2.6 on 2022-07-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0003_housepost_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='housepost',
            name='transaction',
            field=models.CharField(choices=[('Vente', 'Vente'), ('Location (Per Day)', 'Location (Per Day)'), ('Location (Per Month)', 'Location (Per Month)')], default='Vente', max_length=50),
        ),
    ]
