# Generated by Django 3.2.6 on 2022-07-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0005_housepost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='housepost',
            name='viewd',
            field=models.IntegerField(default=0),
        ),
    ]
