# Generated by Django 3.2.6 on 2022-07-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0006_housepost_viewd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housepost',
            name='age_proprety',
        ),
        migrations.AddField(
            model_name='housepost',
            name='bedRoom',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
