# Generated by Django 3.2.6 on 2022-07-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0007_auto_20220705_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepost',
            name='bedRoom',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
