# Generated by Django 3.2.6 on 2022-07-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0009_alter_housepost_titlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepost',
            name='addresse',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='housepost',
            name='titleAd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
