# Generated by Django 3.2.6 on 2022-07-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0010_auto_20220712_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepost',
            name='city',
            field=models.CharField(choices=[('Casablanca', 'Casablanca'), ('Rabat', 'Rabat'), ('Marrakech', 'Marrakech'), ('Agadir', 'Agadir'), ('Sale', 'Sale'), ('Kenitra', 'Kenitra'), ('Meknes', 'Meknes'), ('Oujda', 'Oujda'), ('Temara', 'Temara'), ('El Jadida', 'El Jadida'), ('Mohammedia', 'Mohammedia'), ('Tetouan', 'Tetouan'), ('Nador', 'Nador'), ('Safi', 'Safi'), ('Beni Mellal', 'Beni Mellal'), ('Khouribga', 'Khouribga'), ('Bouznika', 'Bouznika'), ('Settat', 'Settat'), ('Abadou', 'Abadou'), ('Abaynou', 'Abaynou'), ('Agadir', 'Agadir'), ('Agadir Melloul', 'Oujda'), ('Tanger', 'Tanger')], default='Casablanca', max_length=50),
        ),
    ]
