# Generated by Django 3.2.6 on 2022-07-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0012_alter_housepost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepost',
            name='addresse',
            field=models.CharField(max_length=95),
        ),
        migrations.AlterField(
            model_name='housepost',
            name='bedRoom',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='housepost',
            name='living_room',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='housepost',
            name='rooms',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='housepost',
            name='titleAd',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='housepost',
            name='toilettes',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
