# Generated by Django 3.2.6 on 2022-07-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0015_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
    ]
