# Generated by Django 3.2.6 on 2022-08-27 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeApp', '0018_alter_housepost_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housepost',
            name='viewd',
        ),
        migrations.AddField(
            model_name='housepost',
            name='viewd',
            field=models.ManyToManyField(blank=True, related_name='viewdPost', to=settings.AUTH_USER_MODEL),
        ),
    ]
