# Generated by Django 3.2.6 on 2022-08-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0019_auto_20220827_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='housepost',
            name='generated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
