# Generated by Django 4.0.5 on 2022-06-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileaccount',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
