# Generated by Django 4.0.5 on 2022-06-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0003_profileaccount_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileaccount',
            name='phoneNumber',
            field=models.CharField(blank=True, help_text='Enter your Phone number', max_length=12, null=True),
        ),
    ]
