# Generated by Django 3.2.6 on 2022-07-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0004_alter_profileaccount_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileaccount',
            name='bio',
            field=models.TextField(blank=True, default='No Bio', max_length=600, null=True),
        ),
    ]
