# Generated by Django 3.2.6 on 2022-09-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0008_alter_profileaccount_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileaccount',
            name='encryptedField',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
