# Generated by Django 3.2.6 on 2022-09-11 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0009_profileaccount_encryptedfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileaccount',
            name='encryptedField',
        ),
    ]
