# Generated by Django 3.2.6 on 2022-09-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0010_remove_profileaccount_encryptedfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileaccount',
            name='encryptedField',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
